CREATE TABLE [User]
(
	ID INT PRIMARY KEY IDENTITY,
	UserName NVARCHAR(20) NOT NULL,
	Salt NVARCHAR(32) NOT NULL,
	Password NVARCHAR(32) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Nickname NVARCHAR(20) NOT NULL,
	Avatar NVARCHAR(100),
	CreateDate DATETIME NOT NULL,
	Token NVARCHAR(32)
)

CREATE TABLE [Category]
(
	ID INT PRIMARY KEY IDENTITY,
	ParentID INT,
	Name NVARCHAR(50) NOT NULL
)