CREATE TABLE [User]
(
	ID INT PRIMARY KEY IDENTITY,
	UserName NVARCHAR(20) NOT NULL,
	Password NVARCHAR(32) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Nickname NVARCHAR(20) NOT NULL,
	Avatar NVARCHAR(100),
	CreateDate DATETIME NOT NULL,
	Token NVARCHAR(32)
)

CREATE TABLE [Category]
(
	ID INT PRIMARY KEY IDENTITY,
	ParentID INT,
	Name NVARCHAR(50) NOT NULL
)

CREATE TABLE [Article]
(
	ID INT PRIMARY KEY IDENTITY,
	Title NVARCHAR(100) NOT NULL,
	Content NVARCHAR(MAX),
	Summary NVARCHAR(MAX),
	UserID INT NOT NULL,
	[From] NVARCHAR(50),
	PostDate DATETIME NOT NULL,
	Status TINYINT NOT NULL,
	AllowComment BIT NOT NULL
)

CREATE TABLE [CategoryArticle]
(
	CategoryID INT NOT NULL,
	ArticleID INT NOT NULL,
	PRIMARY KEY(CategoryID, ArticleID)
)

CREATE TABLE [Comment]
(
	ID INT PRIMARY KEY IDENTITY,
	ArticleID INT NOT NULL,
	ReplyTo INT,
	Content NVARCHAR(MAX) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Nickname NVARCHAR(20) NOT NULL,
	PostDate DATETIME NOT NULL,
	PostIP NVARCHAR(50) NOT NULL,
	Status TINYINT NOT NULL,
	NotifyOnReply BIT NOT NULL
)